version: "3.9"
services:
  ts-app:
    build: 
      context: ./dev
    ports:
      - ${CONTAINER_PORT}:80
    tty: true
    volumes:
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
      - ${HOME}/.gitconfig:/root/.gitconfig
    restart: unless-stopped  
    networks:
      - my_shared_network  

networks:
  my_shared_network:
    external: true
